name: PyInstaller

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build with pyinstaller
      run: |
        pyinstaller V3.py
    - uses: actions/upload-artifact@v2
      with:
        name: Game0fLife
        path: D:\a\Conways_Game_Of_Life\Conways_Game_Of_Life\build\V3\V3.exe
